// Error codes — docs/api-spec.md §10
export const ErrorCode = {
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_TOKEN: 'INVALID_TOKEN',
  INVALID_REFRESH: 'INVALID_REFRESH',
  REFRESH_EXPIRED: 'REFRESH_EXPIRED',
  REFRESH_REPLAY_DETECTED: 'REFRESH_REPLAY_DETECTED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  BRANCH_HAS_ACTIVE_EMPLOYEES: 'BRANCH_HAS_ACTIVE_EMPLOYEES',
  EMPLOYEE_CODE_TAKEN: 'EMPLOYEE_CODE_TAKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
  INVALID_LOCATION: 'INVALID_LOCATION',
  NOT_ASSIGNED_TO_BRANCH: 'NOT_ASSIGNED_TO_BRANCH',
  NOT_CHECKED_IN_YET: 'NOT_CHECKED_IN_YET',
  ALREADY_CHECKED_OUT: 'ALREADY_CHECKED_OUT',
  TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
